Feature 10: subscription check
Studio-Yandex-Practicum/wildberries_bot_team_1 pull request #10
Opened 2023-06-14 05:38 UTC by Kulikov1

Добавлена функция проверки подписки у пользователя.

2023-06-14 05:46 UTC, Kulikov1 commented
Так как в мастер еще не добавлен менеджер настроек, в utils.py пока что импорт названия канала идет из .env файла. Позже можно будет прокинуть импорт из settings.

2023-06-14 09:17 UTC, Yana-Denisova requested changes
Молодец , так держать. :)

2023-06-14 09:17 UTC, Yana-Denisova commented on tgbot/bot/conversations/main_application.py
> +async def button(update: Update, context: ContextTypes.DEFAULT_TYPE):
давай перенесем этот обработчик в tgbot\bot\handlers.py  там будут все обработчики

2023-06-14 09:17 UTC, Yana-Denisova commented on tgbot/bot/conversations/main_application.py
> +            await query.answer()
```suggestion
            await query.answer("Подписка на канал не найдена")
```

2023-06-16 08:19 UTC, Yana-Denisova requested changes

2023-06-16 08:19 UTC, Yana-Denisova commented on tgbot/bot/utils.py
> +    Для того, чтобы проверка сработала нужно добавить бота в администраторы
Хороший докстринг!

2023-06-16 08:19 UTC, Yana-Denisova commented on tgbot/bot/utils.py
> +CHANNEL_USERNAME = os.getenv('CHANNEL_USERNAME')
Давай код из мастер подтянем и будем брать из сеттингз

2023-06-19 15:38 UTC, Yana-Denisova requested changes
Привет, код в мастере изменился, добавились новые функции и хендлеры, Подтяни актуальную версию из мастер и интегрируй свою фичу в актуальный код .

2023-06-20 08:05 UTC, Yana-Denisova requested changes
Привет, ты точно подтянул самую последнюю версию мастер в свою ветку? У тебя нет хендлеров и команды вынесли в отдельный файл и появилось новое приложение parser.

2023-06-21 00:48 UTC, Kulikov1 commented
Привет. На момент отправки все что было в мастер я подтянул. Приложение парсер есть, хендлеры есть, в отдельном файле команды.

2023-06-21 06:37 UTC, Yana-Denisova approved these changes

2023-06-21 23:09 UTC, merged