feature 16: Создать модель для рассылки
Studio-Yandex-Practicum/wildberries_bot_team_1 pull request #16
Opened 2023-06-18 12:27 UTC by SergParfe

feature 16: Создать модель для рассылки

модель создана, в админку прописана

2023-06-26 12:47 UTC, Yana-Denisova requested changes

2023-06-26 12:47 UTC, Yana-Denisova commented on tgbot/botmanager/models.py
> +User = get_user_model()
В мастере появилось много изменений, потяни актуальную версию кода из мастер в свою ветку и интегрируй туда свой код. Если этого не сделать на этом этапе, то он может не заработать и будут конфликты. После этого обязательно протестируй и удостоверься что код работает. :) Например появилась модель администратора, который будет делать рассылку.

2023-06-27 20:45 UTC, SergParfe commented
Мастер подтянут. Фича работает.

2023-06-28 13:53 UTC, Yana-Denisova requested changes
Когда делаешь рассылку хочется нажать кнопку сохранить, кажется что после этого будет следующий шаг по отправке сообщения, но кнопка отправить рассылку не появляется после этого шага, а становится доступной после нажатия на сохранить и продолжить редактирование.  Надо либо выводить оправку после сохранения или переименовать кнопку сохранить и продолжить редактирование.

2023-06-28 13:53 UTC, Yana-Denisova commented on tgbot/botmanager/models.py
> +        verbose_name = 'Сообщение рассылки'
Может сделаем для множественного Рассылка а для единственного Рассылку ? Мне кажется так более понятно будет

2023-07-02 14:03 UTC, SergParfe commented
косметические правки

2023-07-03 10:58 UTC, Yana-Denisova requested changes
Привет, все хорошо, у нас в фичлисте должны быть заявки со списком пользователей тг и рассылка, но у нас пользователи попали в раздел рассылка, давай в названии вместо рассылка сделаем заявки и рассылка, чтобы им было понятнее. И сможешь ли ты в рамках своей задачи убрать из админки раздел пользователи и группы? Он им пока не нужен и это может их запутать. 

![Рассылка_скрин](https://github.com/Studio-Yandex-Practicum/wildberries_bot_team_1/assets/91561120/8c7192e0-0b91-4127-8594-17e1cdb2e767)

2023-07-03 11:13 UTC, SergParfe commented
В новом коммите исправления

2023-07-03 11:42 UTC, Yana-Denisova approved these changes

2023-07-03 11:42 UTC, merged