Feature20 statistics 2 and 3
Studio-Yandex-Practicum/wildberries_bot_team_1 pull request #31
Opened 2023-06-30 18:59 UTC by lojiver

2023-07-01 11:32 UTC, Yana-Denisova requested changes
![названия](https://github.com/Studio-Yandex-Practicum/wildberries_bot_team_1/assets/91561120/b129e2df-da6e-4c5e-83f9-81f091f5bb38)
Давайте еще добавим человекочитаемые названия

2023-07-01 11:32 UTC, Yana-Denisova commented on tgbot/.data/logs/bot.log.2023-06-28
> +2023-06-28 21:51:17,548, INFO, django.utils.autoreload, Watching for file changes with StatReloader
Давайте добавим логи в гитигнор

2023-07-01 11:32 UTC, Yana-Denisova commented on tgbot/botmanager/templates/statistics.html
> +            <th>Количество запросов</th>
Давай добавим третьим столбцом общее количество запросов по всем юзерам как это ты сделала с пользователями

2023-07-02 18:18 UTC, lojiver commented on tgbot/.data/logs/bot.log.2023-06-28
> +2023-06-28 21:51:17,548, INFO, django.utils.autoreload, Watching for file changes with StatReloader
Модели UserAction вообще не должно быть в админке, я для удобства тестов добавила и забыла убрать, сейчас убрала.

Логи в гитигнор есть в ветке логирования, просто оно как-то не сходится со всеми пуллами-пушами, добавила и здесь

2023-07-02 18:19 UTC, lojiver commented on tgbot/botmanager/templates/statistics.html
> +            <th>Количество запросов</th>
Это довольно нелепо, у нас либо будет таблица, где в третьем столбце во всем строчках одно число (сумма всех запросов), либо числа разные - каждый раз это сумма запросов пользователей, что ниже по алфавиту (это если по аналогии с таблицей пользователей делать, там же кумулятивная сумма) - а это очень бесполезная инфаормация.

Я добавила просто строчки - всего запросов и всего пользователей ниже

2023-07-03 10:18 UTC, Yana-Denisova requested changes
![конпка_начало](https://github.com/Studio-Yandex-Practicum/wildberries_bot_team_1/assets/91561120/756d9bfc-004c-4d17-b33f-9b5fa87784c4)
Конка начало не работает, можно либо поправить, либо убрать вообще, в целом она тут не играет большой роли

2023-07-03 16:10 UTC, Yana-Denisova requested changes
Привет, давай тогда пока оставим кастомизацию как было, время поджимает, лучше его потратить на обработку ошибки. Если открыть раздел статистика, пока еще никто не подписался , то вылезает ошибка ZeroDivisionError at /statistics/ , здорово было бы это обработать .

2023-07-03 19:58 UTC, Yana-Denisova requested changes
Должно получиться как-то так
![подвинем](https://github.com/Studio-Yandex-Practicum/wildberries_bot_team_1/assets/91561120/1c735b8f-067e-4927-85b3-95b4ea5ed460)

2023-07-03 19:58 UTC, Yana-Denisova commented on tgbot/botmanager/templates/statistics.html
>  {% block content %}
Давай перенесем это сюда  начиная с 18 строки и добавим отступ br
```
    <h1>Всего пользователей - {{ all_users }} </h1>
    <h1>Всего запросов - {{ all_requests }} </h1>
    <h1>Запросов на пользователя - {{ requests_for_user }} </h1>
    </br>
```

2023-07-03 19:58 UTC, Yana-Denisova commented on tgbot/botmanager/templates/statistics.html
>      </p>
давай добавим пустую строку для лучшей читаемости 
`<br>`

2023-07-03 19:58 UTC, Yana-Denisova commented on tgbot/botmanager/templates/statistics.html
>      </p>
Давай тут тоже добавим `<br>`

2023-07-04 06:57 UTC, Yana-Denisova approved these changes

2023-07-04 07:59 UTC, merged