feature 2: set up pre-commit
Studio-Yandex-Practicum/wildberries_bot_team_1 pull request #4
Opened 2023-06-10 12:06 UTC by SergParfe

feature 2: Настроить pre-commit и параметры форматирования.

Внесены настройки для isort и flake8. Добавлена папка .vscode в gitignore

2023-06-10 17:56 UTC, Yana-Denisova requested changes
files: ^(bot/|core/|src/) задает регулярное выражение для фильтрации файлов, на которых должны выполняться хуки pre-commit.

Регулярное выражение ^(bot/|core/|src/) указывает на следующее

^ - начало строки.
(bot/|core/|src/) - указывает на три возможные подстроки: "bot/", "core/" или "src/".
Таким образом, строка files:  указывает, что файлы, пути к которым начинаются с "bot/", "core/" или "src/", должны быть включены для обработки хуками pre-commit.

2023-06-10 17:56 UTC, Yana-Denisova commented on pyproject.toml
> +extend-ignore = """
А почему решил убрать эти проверки W503, E203, E701? Это же антипаттерны, разве нет? Или ты видишь ситуации, где это необходимо? Если да то напиши пожалуйста, просто для понимания.

2023-06-10 17:56 UTC, Yana-Denisova commented on .pre-commit-config.yaml
> +      files: ^(bot/|core/|src/)
у нас пока нет core и src, давай обновим эту строку под наш проект

2023-06-10 17:56 UTC, Yana-Denisova commented on pyproject.toml
> +multi_line_output = 3
```suggestion
default_section = "THIRDPARTY"
sections = ["STDLIB", "FIRSTPARTY", "THIRDPARTY", "LOCALFOLDER"]
known_local_folder = ["tgbot", "bot", "botmanager"]
lines_after_imports = "2"
skip = ["tests", ".venv", "venv"]
line_length = "79"
multi_line_output = "3"
include_trailing_comma = "true"
use_parentheses = "true"
```

2023-06-10 17:56 UTC, Yana-Denisova commented on pyproject.toml
> +    per-file-ignores = """
Почему тут такие отступы? :)

2023-06-10 17:56 UTC, Yana-Denisova commented on .pre-commit-config.yaml
> +      files: ^(bot/|core/|src/)
Не подходит под наш проект

2023-06-11 07:01 UTC, SergParfe commented on pyproject.toml
> +extend-ignore = """
ошибка копипасты

2023-06-11 07:04 UTC, SergParfe commented
замечания исправлены

2023-06-11 11:57 UTC, Yana-Denisova requested changes

2023-06-11 11:57 UTC, Yana-Denisova commented on pyproject.toml
>  exclude = ".venv"
Давай добавим сюда строку paths = ["./tgbot", "./bot", "./botmanager"]

2023-06-11 11:57 UTC, Yana-Denisova commented on .pre-commit-config.yaml
> +      files: ^(bot/)
давай сюда добавим ^(tgbot/ | bot/ | botmanager/)

2023-06-11 11:57 UTC, Yana-Denisova commented on .pre-commit-config.yaml
> +      files: ^(bot/)
давай сюда добавим ^(tgbot/ | bot/ | botmanager/)

2023-06-11 11:58 UTC, Yana-Denisova commented
Давай еще название поменяем на feature 2: set up pre-commit

2023-06-11 12:02 UTC, SergParfe commented
voilà

2023-06-11 12:21 UTC, Yana-Denisova approved these changes

2023-06-11 12:22 UTC, merged