Feature 7: settings manager with pydantic
Studio-Yandex-Practicum/wildberries_bot_team_1 pull request #7
Opened 2023-06-13 02:26 UTC by Kulikov1

2023-06-13 08:29 UTC, Yana-Denisova commented
Давай добавим описание к пуллреквесту

2023-06-14 00:45 UTC, Kulikov1 commented on tgbot/bot/core/settings.py
> +        env_file_encoding = 'utf-8'
Добавил в конце файла settings = Settings(). Изменил def Config(): на class Config:. Добавил load_dotenv().

2023-06-15 10:01 UTC, Yana-Denisova requested changes

2023-06-15 23:31 UTC, Kulikov1 commented on tgbot/bot/core/settings.py
> +load_dotenv()
Странно, без этого раньше не работало. Так же наткнулся на информацию, что .env должен лежать в одной директории с settings,  чтобы все работало без load_dotenv. Сейчас удалил и все работает, чудеса.....

2023-06-16 08:12 UTC, Yana-Denisova approved these changes

2023-06-16 08:12 UTC, merged