Make readme
Studio-Yandex-Practicum/wildberries_bot_team_1 pull request #9
Opened 2023-06-13 18:48 UTC by lojiver

2023-06-13 20:53 UTC, Yana-Denisova requested changes
Так же давай добавим описание к пуллреквесту и поменяем название , пример можно посмотреть у ребят в их пуллреквестах

2023-06-13 20:53 UTC, Yana-Denisova commented on README.md
> +Установить зависимости из файла requirements.txt:
мы в проекте используем poetry для управления зависимости, давай поменяем и добавим инфу по pre-commit

2023-06-13 20:53 UTC, Yana-Denisova commented on pyproject.toml
> +authors = ["Сергей Шубин", "Сергей Парфенов", "Андрей Куликов", "Анна Горбунова", "Артемий Березин", "Кирилл Молчанов"]
Меня тоже надо вписать

2023-06-13 20:53 UTC, Yana-Denisova commented on README.md
> +[![Praktikum](https://yastatic.net/q/logoaas/v2/%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81.svg?circle=black&color=000&first=white)](https://practicum.yandex.ru/profile/backend-developer/) [![Praktikum](htt
Давай уберем про команду студентов(это уже не учебный проект,  мы его потом передадим заказчику) и сделаем больше про описание самого бота и его возможностей, можно инфу взять из ноушн

2023-06-14 18:12 UTC, lojiver commented on README.md
> +Установить зависимости из файла requirements.txt:
написала в Пачке тоже - а зачем нам тогда файл requirements.txt в проекте? В ношене прям задача на его подготовку же есть, в readme инструкция для того, кто будет разворачивать проект у себя на компе, он не будет коммитить ничего, если мы requirements сделали, зачем внешнего пользователя в поетри гнать вообще?

2023-06-14 21:16 UTC, Yana-Denisova approved these changes

2023-06-15 15:59 UTC, merged